# ################################
# What we published at Interspeech24 + dropout
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 2001
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/best-relu-dropout/<seed>
output_wer_folder: !ref <output_folder>/
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

output_transcription: !ref <output_folder>/output_{dataset}.json
transcribe_dataloader_opts:
   batch_size: !ref <test_batch_size>


to_transcribe:
   test: 
      data_folder: /data/coros2/ProjetPathoLoc/Patho/Work/RUGBI/PHD/Bref/wav
      transcription_dataset: /data/coros1/mmaisonneuve/datasets/bref/test.csv
   hc_lec:
      data_folder: /data/coros1/mmaisonneuve/c2si-wav-16kHz
      transcription_dataset: /data/coros1/mmaisonneuve/datasets/c2si/hc-lec-without-alp-test.csv
   hc_dap:
      data_folder: /data/coros1/mmaisonneuve/c2si-wav-16kHz
      transcription_dataset: /data/coros1/mmaisonneuve/datasets/c2si/hc-dap-without-alp-test.csv
   patients_lec:
      data_folder: /data/coros1/mmaisonneuve/c2si-wav-16kHz
      transcription_dataset: /data/coros1/mmaisonneuve/datasets/c2si/patients-lec-test.csv
   patients_dap:
      data_folder: /data/coros1/mmaisonneuve/c2si-wav-16kHz
      transcription_dataset: /data/coros1/mmaisonneuve/datasets/c2si/patients-dap-test.csv

# Using the 14k wav2vec model fine-tuned on French language ONLY
# wav2vec2_hub: LeBenchmark/wav2vec2-FR-14K-large
wav2vec2_hub: LeBenchmark/wav2vec2-FR-3K-large
wav2vec2_folder: !ref <save_folder>/wav2vec2_checkpoint

# Data files
data_folder: /data/coros2/ProjetPathoLoc/Patho/Work/RUGBI/PHD/Bref/wav
cp_data_folder: /data/coros1/mmaisonneuve/CommonPhone/CP/fr/wav # CommonPhone audios

ckpt_interval_minutes: 25 # save checkpoint every N min
dataset_folder: /data/coros1/mmaisonneuve/datasets/bref+cp/with_accents
train_csv: !ref <dataset_folder>/train.csv
valid_csv: !ref <dataset_folder>/validation.csv
test_csv: !ref <dataset_folder>/test.csv
segment_length: 2032 # frames, math.floor((5 * 1000 / 49 + 25) * 16)

# Training parameters
number_of_epochs: 15 
lr: 0.9
lr_wav2vec: 0.0001
sorting: ascending
auto_mix_prec: False
sample_rate: 16000

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# Must be 3 per GPU to fit 32GB of VRAM
batch_size: 1024
test_batch_size: 1024

# Dataloader options
train_dataloader_opts:
   batch_size: !ref <batch_size>

valid_dataloader_opts:
   batch_size: !ref <batch_size>

test_dataloader_opts:
   batch_size: !ref <test_batch_size>

# Model parameters
activation: !name:torch.nn.ReLU
dnn_layers: 3
dnn_neurons: 1024
freeze_wav2vec: False

# Outputs
output_neurons: 32  # 31 phones and silence in BREF

#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
   limit: !ref <number_of_epochs>

dropout: !new:torch.nn.Dropout
   p: 0.4

wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
   source: !ref <wav2vec2_hub>
   freeze: !ref <freeze_wav2vec>
   save_path: !ref <wav2vec2_folder>


classifier: !new:classifier.Classifier
   input_shape: [null, 6144]
   neurons: !ref <dnn_neurons>
   layers: !ref <dnn_layers>
   activation: !ref <activation>
   dropout: !ref <dropout>

final_layer: !new:speechbrain.nnet.linear.Linear
   input_size: !ref <dnn_neurons>
   n_neurons: !ref <output_neurons>

modules:
   wav2vec2: !ref <wav2vec2>
   classifier: !ref <classifier>
   final_layer: !ref <final_layer>

model: !new:torch.nn.ModuleList
   - [!ref <classifier>, !ref <final_layer>]

model_opt_class: !name:torch.optim.Adadelta
   lr: !ref <lr>
   rho: 0.95
   eps: 1.e-8

wav2vec_opt_class: !name:torch.optim.Adam
   lr: !ref <lr_wav2vec>

lr_annealing_model: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr>
   improvement_threshold: 0.0025
   annealing_factor: 0.8
   patient: 0

lr_annealing_wav2vec: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr_wav2vec>
   improvement_threshold: 0.0025
   annealing_factor: 0.9
   patient: 0

label_encoder: !new:speechbrain.dataio.encoder.CTCTextEncoder

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
   checkpoints_dir: !ref <save_folder>
   recoverables:
      wav2vec2: !ref <wav2vec2>
      model: !ref <model>
      scheduler_model: !ref <lr_annealing_model>
      scheduler_wav2vec: !ref <lr_annealing_wav2vec>
      counter: !ref <epoch_counter>
      tokenizer: !ref <label_encoder>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
